# Generated by Django 3.2.5 on 2022-06-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220602_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Date_Check_In',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Date_Check_Out',
            field=models.DateField(),
        ),
    ]
