# Generated by Django 3.2.5 on 2022-06-01 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220602_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Date_Check_In',
            field=models.DateField(default=datetime.date(2022, 6, 2)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Date_Check_Out',
            field=models.DateField(default=datetime.date(2022, 6, 2)),
        ),
    ]
